<a href="https://colab.research.google.com/github/BenCoop16/IS-477/blob/main/IS477_Proj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
import requests
import pandas as pd
import datetime
import time
import yfinance as yf
import time
from google.colab import files
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [73]:
all_posts = []
batch_after = "2024-01-01"
batch_before = "2026-01-01"

for i in range(20):
    params = {"subreddit": "Bitcoin", "after": batch_after, "before": batch_before, "limit": 100, "sort": "asc"}
    response = requests.get(url, params=params)
    posts = response.json()
    batch = posts['data']
    if not batch:
        print(f"No more data at batch {i}")
        break
    all_posts.extend(batch)
    batch_after = batch[-1]['created_utc']
    print(f"Batch {i+1}: {len(batch)} posts, total so far: {len(all_posts)}")
    time.sleep(1)

df_bitcoin = pd.DataFrame(all_posts)[['id', 'title', 'selftext', 'score', 'upvote_ratio', 'num_comments', 'created_utc', 'subreddit']]
df_bitcoin['timestamp'] = pd.to_datetime(df_bitcoin['created_utc'], unit='s')
print(df_bitcoin.shape)

Batch 1: 100 posts, total so far: 100
Batch 2: 100 posts, total so far: 200
Batch 3: 100 posts, total so far: 300
Batch 4: 100 posts, total so far: 400
Batch 5: 100 posts, total so far: 500
Batch 6: 100 posts, total so far: 600
Batch 7: 100 posts, total so far: 700
Batch 8: 100 posts, total so far: 800
Batch 9: 100 posts, total so far: 900
Batch 10: 100 posts, total so far: 1000
Batch 11: 100 posts, total so far: 1100
Batch 12: 100 posts, total so far: 1200
Batch 13: 100 posts, total so far: 1300
Batch 14: 100 posts, total so far: 1400
Batch 15: 100 posts, total so far: 1500
Batch 16: 100 posts, total so far: 1600
Batch 17: 100 posts, total so far: 1700
Batch 18: 100 posts, total so far: 1800
Batch 19: 100 posts, total so far: 1900
Batch 20: 100 posts, total so far: 2000
(2000, 9)

In [51]:
df_bitcoin = pd.DataFrame(posts['data'])
df_bitcoin = df_bitcoin[['id', 'title', 'selftext', 'score', 'upvote_ratio', 'num_comments', 'created_utc', 'subreddit']]
df_bitcoin['timestamp'] = pd.to_datetime(df_bitcoin['created_utc'], unit='s')
df_bitcoin = df_bitcoin.drop(columns=['created_utc'])
df_bitcoin.to_csv('reddit_bitcoin_raw.csv', index=False)

In [52]:
df_bitcoin.head()

,id,title,selftext,score,upvote_ratio,num_comments,subreddit,timestamp
0,1913s4n,Time to Break Free,,1,1.00,0,Bitcoin,2024-01-07 21:55:30
1,19148ol,Just get off zero ( JGOZ ),,1,1.00,0,Bitcoin,2024-01-07 22:13:43
2,1914fzt,I found a yellow key on keys.lol,"According to chatgpt, the odds are like winnin...",4,0.67,8,Bitcoin,2024-01-07 22:21:44
3,1914pto,EARN 10x YOUR INVESTMENT WITH ANTMINER,[removed],1,1.00,0,Bitcoin,2024-01-07 22:32:56
4,1914v8g,51% attack,what is to stop bad actors from executing this...,1,0.44,12,Bitcoin,2024-01-07 22:39:11

In [53]:
df_price = yf.download("BTC-USD", start="2024-01-01", end="2026-01-01")
df_price.to_csv('crypto_prices_raw.csv')

/tmp/ipykernel_10803/4184534066.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_price = yf.download("BTC-USD", start="2024-01-01", end="2026-01-01")
[*********************100%***********************]  1 of 1 completed

In [54]:
df_price.head()

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Date,,,,,
2024-01-01,44167.332031,44175.437500,42214.976562,42280.234375,18426978443
2024-01-02,44957.968750,45899.707031,44176.949219,44187.140625,39335274536
2024-01-03,42848.175781,45503.242188,40813.535156,44961.601562,46342323118
2024-01-04,44179.921875,44770.023438,42675.175781,42855.816406,30448091210
2024-01-05,44162.691406,44353.285156,42784.718750,44192.980469,32336029347

In [72]:
###Data files acquired/created and uploaded to GitHub

In [57]:
print(df_bitcoin.shape)
print(df_price.shape)
print(df_bitcoin.head())
print(df_price.head())

(100, 8)
(731, 5)
        id                                   title  \
0  1913s4n                      Time to Break Free
1  19148ol              Just get off zero ( JGOZ )
2  1914fzt        I found a yellow key on keys.lol
3  1914pto  EARN 10x YOUR INVESTMENT WITH ANTMINER
4  1914v8g                              51% attack

                                            selftext  score  upvote_ratio  \
0                                                         1          1.00
1                                                         1          1.00
2  According to chatgpt, the odds are like winnin...      4          0.67
3                                          [removed]      1          1.00
4  what is to stop bad actors from executing this...      1          0.44

   num_comments subreddit           timestamp
0             0   Bitcoin 2024-01-07 21:55:30
1             0   Bitcoin 2024-01-07 22:13:43
2             8   Bitcoin 2024-01-07 22:21:44
3             0   Bitcoin 2024-01-07 22:32:56
4            12   Bitcoin 2024-01-07 22:39:11
Price              Close          High           Low          Open  \
Ticker           BTC-USD       BTC-USD       BTC-USD       BTC-USD
Date
2024-01-01  44167.332031  44175.437500  42214.976562  42280.234375
2024-01-02  44957.968750  45899.707031  44176.949219  44187.140625
2024-01-03  42848.175781  45503.242188  40813.535156  44961.601562
2024-01-04  44179.921875  44770.023438  42675.175781  42855.816406
2024-01-05  44162.691406  44353.285156  42784.718750  44192.980469

Price            Volume
Ticker          BTC-USD
Date
2024-01-01  18426978443
2024-01-02  39335274536
2024-01-03  46342323118
2024-01-04  30448091210
2024-01-05  32336029347

In [59]:
print("Duplicates:", df_bitcoin.duplicated(subset='id').sum())
print("\nMissing values:")
print(df_bitcoin.isnull().sum())
print("\nRemoved posts (selftext is [removed]):", (df_bitcoin['selftext'] == '[removed]').sum())
print("Deleted posts (selftext is [deleted]):", (df_bitcoin['selftext'] == '[deleted]').sum())

Duplicates: 0

Missing values:
id              0
title           0
selftext        0
score           0
upvote_ratio    0
num_comments    0
created_utc     0
subreddit       0
timestamp       0
dtype: int64

Removed posts (selftext is [removed]): 364
Deleted posts (selftext is [deleted]): 10

In [60]:
df_bitcoin_clean = df_bitcoin[df_bitcoin['selftext'] != '[removed]']
df_bitcoin_clean = df_bitcoin_clean[df_bitcoin_clean['selftext'] != '[deleted]']
df_bitcoin_clean = df_bitcoin_clean.drop(columns=['created_utc'])
df_bitcoin_clean = df_bitcoin_clean.reset_index(drop=True)
print(df_bitcoin_clean.shape)

(1626, 8)

In [61]:
print("Duplicates:", df_price.duplicated().sum())
print("\nMissing values:")
print(df_price.isnull().sum())
print("\nPrice data types:")
print(df_price.dtypes)

Duplicates: 0

Missing values:
Price   Ticker
Close   BTC-USD    0
High    BTC-USD    0
Low     BTC-USD    0
Open    BTC-USD    0
Volume  BTC-USD    0
dtype: int64

Price data types:
Price   Ticker
Close   BTC-USD    float64
High    BTC-USD    float64
Low     BTC-USD    float64
Open    BTC-USD    float64
Volume  BTC-USD      int64
dtype: object

In [62]:
df_price_clean = df_price.copy()
df_price_clean.columns = ['close', 'high', 'low', 'open', 'volume']
df_price_clean = df_price_clean.reset_index()
df_price_clean.columns = ['date', 'close', 'high', 'low', 'open', 'volume']
df_price_clean['date'] = pd.to_datetime(df_price_clean['date'])
print(df_price_clean.head())
print(df_price_clean.dtypes)

        date         close          high           low          open  \
0 2024-01-01  44167.332031  44175.437500  42214.976562  42280.234375
1 2024-01-02  44957.968750  45899.707031  44176.949219  44187.140625
2 2024-01-03  42848.175781  45503.242188  40813.535156  44961.601562
3 2024-01-04  44179.921875  44770.023438  42675.175781  42855.816406
4 2024-01-05  44162.691406  44353.285156  42784.718750  44192.980469

        volume
0  18426978443
1  39335274536
2  46342323118
3  30448091210
4  32336029347
date      datetime64[ns]
close            float64
high             float64
low              float64
open             float64
volume             int64
dtype: object

In [63]:
df_bitcoin_clean['date'] = df_bitcoin_clean['timestamp'].dt.normalize()
df_daily_reddit = df_bitcoin_clean.groupby('date').agg(
    post_count=('id', 'count'),
    avg_score=('score', 'mean'),
    avg_upvote_ratio=('upvote_ratio', 'mean'),
    avg_comments=('num_comments', 'mean')
).reset_index()
print(df_daily_reddit.shape)
print(df_daily_reddit.head())

(8, 5)
        date  post_count  avg_score  avg_upvote_ratio  avg_comments
0 2024-01-01         144   2.701389          0.960000     21.965278
1 2024-01-02         311   2.090032          0.980965     21.019293
2 2024-01-03         276   1.134058          0.983225     14.391304
3 2024-01-04         216   2.699074          0.985417     17.185185
4 2024-01-05         204   1.186275          0.990539     23.612745

In [64]:
print("Reddit date range:")
print(df_bitcoin_clean['timestamp'].min())
print(df_bitcoin_clean['timestamp'].max())

Reddit date range:
2024-01-01 00:02:31
2024-01-08 07:38:02

In [65]:
all_posts = []
months = pd.date_range(start="2024-01-01", end="2026-01-01", freq="MS")

for i in range(len(months) - 1):
    batch_after = months[i].strftime("%Y-%m-%d")
    batch_before = months[i+1].strftime("%Y-%m-%d")
    params = {"subreddit": "Bitcoin", "after": batch_after, "before": batch_before, "limit": 100, "sort": "asc"}
    response = requests.get(url, params=params)
    posts = response.json()
    batch = posts['data']
    if batch:
        all_posts.extend(batch)
    print(f"{batch_after}: {len(batch) if batch else 0} posts, total: {len(all_posts)}")
    time.sleep(1)

print("Total posts:", len(all_posts))

2024-01-01: 100 posts, total: 100
2024-02-01: 100 posts, total: 200
2024-03-01: 100 posts, total: 300
2024-04-01: 100 posts, total: 400
2024-05-01: 100 posts, total: 500
2024-06-01: 100 posts, total: 600
2024-07-01: 100 posts, total: 700
2024-08-01: 100 posts, total: 800
2024-09-01: 100 posts, total: 900
2024-10-01: 100 posts, total: 1000
2024-11-01: 100 posts, total: 1100
2024-12-01: 100 posts, total: 1200
2025-01-01: 100 posts, total: 1300
2025-02-01: 100 posts, total: 1400
2025-03-01: 100 posts, total: 1500
2025-04-01: 100 posts, total: 1600
2025-05-01: 100 posts, total: 1700
2025-06-01: 100 posts, total: 1800
2025-07-01: 100 posts, total: 1900
2025-08-01: 100 posts, total: 2000
2025-09-01: 100 posts, total: 2100
2025-10-01: 100 posts, total: 2200
2025-11-01: 100 posts, total: 2300
2025-12-01: 100 posts, total: 2400
Total posts: 2400

In [66]:
df_bitcoin = pd.DataFrame(all_posts)[['id', 'title', 'selftext', 'score', 'upvote_ratio', 'num_comments', 'created_utc', 'subreddit']]
df_bitcoin['timestamp'] = pd.to_datetime(df_bitcoin['created_utc'], unit='s')
df_bitcoin_clean = df_bitcoin[df_bitcoin['selftext'] != '[removed]']
df_bitcoin_clean = df_bitcoin_clean[df_bitcoin_clean['selftext'] != '[deleted]']
df_bitcoin_clean = df_bitcoin_clean.drop(columns=['created_utc'])
df_bitcoin_clean = df_bitcoin_clean.reset_index(drop=True)
df_bitcoin_clean['date'] = df_bitcoin_clean['timestamp'].dt.normalize()
df_daily_reddit = df_bitcoin_clean.groupby('date').agg(
    post_count=('id', 'count'),
    avg_score=('score', 'mean'),
    avg_upvote_ratio=('upvote_ratio', 'mean'),
    avg_comments=('num_comments', 'mean')
).reset_index()
print(df_daily_reddit.shape)
print(df_daily_reddit.head())

(24, 5)
        date  post_count  avg_score  avg_upvote_ratio  avg_comments
0 2024-01-01          81   3.333333          0.946914     22.987654
1 2024-02-01          83  37.313253          0.702892     14.084337
2 2024-03-01          79  35.848101          0.981139     14.886076
3 2024-04-01          81  19.123457          0.693086     18.123457
4 2024-05-01          81  32.432099          0.667901     18.530864

In [67]:
df_price_monthly = df_price_clean.copy()
df_price_monthly['date'] = df_price_monthly['date'].dt.to_period('M').dt.to_timestamp()
df_price_monthly = df_price_monthly.groupby('date').agg(
    avg_close=('close', 'mean'),
    avg_volume=('volume', 'mean'),
    price_change=('close', lambda x: x.iloc[-1] - x.iloc[0])
).reset_index()
df_merged = pd.merge(df_daily_reddit, df_price_monthly, on='date', how='inner')
print(df_merged.shape)
print(df_merged.head())

(24, 8)
        date  post_count  avg_score  avg_upvote_ratio  avg_comments  \
0 2024-01-01          81   3.333333          0.946914     22.987654
1 2024-02-01          83  37.313253          0.702892     14.084337
2 2024-03-01          79  35.848101          0.981139     14.886076
3 2024-04-01          81  19.123457          0.693086     18.123457
4 2024-05-01          81  32.432099          0.667901     18.530864

      avg_close    avg_volume  price_change
0  42919.612399  2.664255e+10  -1584.726562
1  49875.174300  2.864558e+10  18122.609375
2  67702.439264  4.665864e+10   8893.015625
3  65882.380599  3.386894e+10  -9065.292969
4  65266.317288  2.820295e+10   9237.402344

In [68]:
df_bitcoin_clean.to_csv('reddit_bitcoin_clean.csv', index=False)
df_price_clean.to_csv('crypto_prices_clean.csv', index=False)
df_merged.to_csv('merged_data.csv', index=False)
print("All files saved!")

All files saved!

In [76]:
analyzer = SentimentIntensityAnalyzer()
df_bitcoin_clean['sentiment'] = df_bitcoin_clean['title'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
print(df_bitcoin_clean[['title', 'sentiment']].head(10))

                                               title  sentiment
0  Anyone using AI legitimately to trade better? ...     0.4404
1                       ETF approval, demand change?     0.3818
2  Mass Adoption after Mass Awareness - We are ge...     0.0000
3                                Bitcoin Yearly Lows    -0.2023
4                       Happy new year motherfuckers     0.5719
5  On the Lightning Network does the node operato...     0.3400
6                              This is where it ends     0.0000
7  Best place to store your Bitcoin from Coinbase...     0.8442
8  Yo why the Bitcoin fees so high right now is t...     0.0000
9                             Happy new year to all!     0.6114